
package com.example.TestTask.TestTaskXmlService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsersPort", targetNamespace = "http://localhost:8082")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsersPort {


    /**
     * 
     * @param getUserByLoginWithRolesRequest
     * @return
     *     returns com.example.TestTask.TestTaskXmlService.GetUserByLoginWithRolesResponse
     */
    @WebMethod
    @WebResult(name = "getUserByLoginWithRolesResponse", targetNamespace = "http://localhost:8082", partName = "getUserByLoginWithRolesResponse")
    public GetUserByLoginWithRolesResponse getUserByLoginWithRoles(
        @WebParam(name = "getUserByLoginWithRolesRequest", targetNamespace = "http://localhost:8082", partName = "getUserByLoginWithRolesRequest")
        GetUserByLoginWithRolesRequest getUserByLoginWithRolesRequest);

    /**
     * 
     * @param addNewUserWithRolesRequest
     * @return
     *     returns com.example.TestTask.TestTaskXmlService.AddNewUserWithRolesResponse
     */
    @WebMethod(operationName = "AddNewUserWithRoles")
    @WebResult(name = "AddNewUserWithRolesResponse", targetNamespace = "http://localhost:8082", partName = "AddNewUserWithRolesResponse")
    public AddNewUserWithRolesResponse addNewUserWithRoles(
        @WebParam(name = "AddNewUserWithRolesRequest", targetNamespace = "http://localhost:8082", partName = "AddNewUserWithRolesRequest")
        AddNewUserWithRolesRequest addNewUserWithRolesRequest);

    /**
     * 
     * @param addFromIdRequest
     * @return
     *     returns com.example.TestTask.TestTaskXmlService.AddFromIdResponse
     */
    @WebMethod(operationName = "AddFromId")
    @WebResult(name = "AddFromIdResponse", targetNamespace = "http://localhost:8082", partName = "AddFromIdResponse")
    public AddFromIdResponse addFromId(
        @WebParam(name = "AddFromIdRequest", targetNamespace = "http://localhost:8082", partName = "AddFromIdRequest")
        AddFromIdRequest addFromIdRequest);

    /**
     * 
     * @param getListUsersWithoutRolesRequest
     * @return
     *     returns com.example.TestTask.TestTaskXmlService.GetListUsersWithoutRolesResponse
     */
    @WebMethod
    @WebResult(name = "getListUsersWithoutRolesResponse", targetNamespace = "http://localhost:8082", partName = "getListUsersWithoutRolesResponse")
    public GetListUsersWithoutRolesResponse getListUsersWithoutRoles(
        @WebParam(name = "getListUsersWithoutRolesRequest", targetNamespace = "http://localhost:8082", partName = "getListUsersWithoutRolesRequest")
        Object getListUsersWithoutRolesRequest);

    /**
     * 
     * @param deleteUserByLoginRequest
     * @return
     *     returns com.example.TestTask.TestTaskXmlService.DeleteUserByLoginResponse
     */
    @WebMethod
    @WebResult(name = "deleteUserByLoginResponse", targetNamespace = "http://localhost:8082", partName = "deleteUserByLoginResponse")
    public DeleteUserByLoginResponse deleteUserByLogin(
        @WebParam(name = "deleteUserByLoginRequest", targetNamespace = "http://localhost:8082", partName = "deleteUserByLoginRequest")
        DeleteUserByLoginRequest deleteUserByLoginRequest);

}
