
package com.example.TestTask.TestTaskXmlService;

import com.example.TestTask.TestTaskXmlService.DeleteUserByLoginRequest;
import com.example.TestTask.TestTaskXmlService.DeleteUserByLoginResponse;
import com.example.TestTask.TestTaskXmlService.GetListUsersWithoutRolesResponse;
import com.example.TestTask.TestTaskXmlService.GetUserByLoginWithRolesRequest;
import com.example.TestTask.TestTaskXmlService.GetUserByLoginWithRolesResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsersPort", targetNamespace = "http://localhost:8082")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsersPort {


    /**
     * 
     * @param editUserRequest
     * @return
     *     returns com.example.TestTask.TestTaskXmlService.EditUserResponse
     */
    @WebMethod(operationName = "EditUser")
    @WebResult(name = "EditUserResponse", targetNamespace = "http://localhost:8082", partName = "EditUserResponse")
    public EditUserResponse editUser(
        @WebParam(name = "EditUserRequest", targetNamespace = "http://localhost:8082", partName = "EditUserRequest")
        EditUserRequest editUserRequest);

    /**
     * 
     * @param getUserByLoginWithRolesRequest
     * @return
     *     returns GetUserByLoginWithRolesResponse
     */
    @WebMethod
    @WebResult(name = "getUserByLoginWithRolesResponse", targetNamespace = "http://localhost:8082", partName = "getUserByLoginWithRolesResponse")
    public GetUserByLoginWithRolesResponse getUserByLoginWithRoles(
        @WebParam(name = "getUserByLoginWithRolesRequest", targetNamespace = "http://localhost:8082", partName = "getUserByLoginWithRolesRequest")
                GetUserByLoginWithRolesRequest getUserByLoginWithRolesRequest);

    /**
     * 
     * @param addNewUserWithRolesRequest
     * @return
     *     returns com.example.TestTask.TestTaskXmlService.AddNewUserWithRolesResponse
     */
    @WebMethod(operationName = "AddNewUserWithRoles")
    @WebResult(name = "AddNewUserWithRolesResponse", targetNamespace = "http://localhost:8082", partName = "AddNewUserWithRolesResponse")
    public AddNewUserWithRolesResponse addNewUserWithRoles(
        @WebParam(name = "AddNewUserWithRolesRequest", targetNamespace = "http://localhost:8082", partName = "AddNewUserWithRolesRequest")
        AddNewUserWithRolesRequest addNewUserWithRolesRequest);

    /**
     * 
     * @param getListUsersWithoutRolesRequest
     * @return
     *     returns GetListUsersWithoutRolesResponse
     */
    @WebMethod
    @WebResult(name = "getListUsersWithoutRolesResponse", targetNamespace = "http://localhost:8082", partName = "getListUsersWithoutRolesResponse")
    public GetListUsersWithoutRolesResponse getListUsersWithoutRoles(
        @WebParam(name = "getListUsersWithoutRolesRequest", targetNamespace = "http://localhost:8082", partName = "getListUsersWithoutRolesRequest")
        Object getListUsersWithoutRolesRequest);

    /**
     * 
     * @param deleteUserByLoginRequest
     * @return
     *     returns DeleteUserByLoginResponse
     */
    @WebMethod
    @WebResult(name = "deleteUserByLoginResponse", targetNamespace = "http://localhost:8082", partName = "deleteUserByLoginResponse")
    public DeleteUserByLoginResponse deleteUserByLogin(
        @WebParam(name = "deleteUserByLoginRequest", targetNamespace = "http://localhost:8082", partName = "deleteUserByLoginRequest")
                DeleteUserByLoginRequest deleteUserByLoginRequest);

}
